// Package lists embeds the built-in server list and Fake SNI presets.
package lists

import (
	"embed"
	"strings"
)

// BuiltinJSON is lists/servers.json, generated by tools/genservers.
//
//go:embed servers.json
var BuiltinJSON []byte

// DNSCryptMD and DNSCryptSig are the DNSCrypt public resolvers list and
// its minisign signature, refreshed by tools/fetchdnscrypt at each release.
// They are used until the first download, which can come late or fail.
//
//go:embed dnscrypt/public-resolvers.md
var DNSCryptMD []byte

//go:embed dnscrypt/public-resolvers.md.minisig
var DNSCryptSig []byte

// FakeSNIPresets holds the built-in copies of lists/fakesni/*.txt and their
// .sig files, used when a preset has never been downloaded. The app checks
// the signature before using one.
//
//go:embed fakesni
var FakeSNIPresets embed.FS

// FakeSNIPresetBase is where presets are downloaded from.
const FakeSNIPresetBase = "https://raw.githubusercontent.com/sickyturtlez/vinpn/main/lists/fakesni/"

// FakeSNIFallback returns the built-in copy (and signature, if any) of the
// preset at url.
func FakeSNIFallback(url string) (data, sig []byte, ok bool) {
	name, found := strings.CutPrefix(url, FakeSNIPresetBase)
	if !found || strings.ContainsAny(name, `/\`) {
		return nil, nil, false
	}
	data, err := FakeSNIPresets.ReadFile("fakesni/" + name)
	if err != nil {
		return nil, nil, false
	}
	sig, _ = FakeSNIPresets.ReadFile("fakesni/" + name + ".sig")
	return data, sig, true
}
